### ISSUE TITLE
Regarding WRF input issues

### ISSUE THREAD

**Issue by kam3545** [lkugler/RTTOV-WRF#1]
Hi,
The code is not working with the WRF model outputs when values are not realistic like negative or undefine values of cloud, ice,  cloud fraction, TSK,  etc. 
What should be the undefine values in these cases that need to add in rttov_wrf.py?  
Thanks

**Comment by lkugler** [comment]
Cloud variables are essential for the output of RTTOV, i.e. cloud-affected brightness temperatures and reflectance values. If you don't have them, see that you get them or ask why they are invalid. As a last resort, you can assume values, depending on your assumption (e.g. no clouds: zero CFRAC, etc)
Is this helpful?

**Comment by kam3545** [comment]
@lkugler, Thanks for your response.
May be I was not clear last time. I have all the required parameters from the WRF forecasts.
BUT in the WRF model, values of required parameters are undefined for some locations. Due to this, I found run time error in code.
My query is regarding this issue. Can I use/define some check to avoid this run-time error.

Thanks
Prashant
